# Generated by Django 4.0 on 2022-12-29 17:37

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landlords', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, size=None)),
                ('number_of_persons', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('map_link', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('owner', models.PositiveIntegerField(blank=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landlords.listings')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.PositiveIntegerField(blank=True)),
                ('images', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, size=None)),
                ('number_of_persons', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=100, null=True)),
                ('map_link', models.CharField(blank=True, max_length=500, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('price', models.CharField(blank=True, max_length=100)),
                ('checked_in', models.BooleanField(default=False)),
                ('owner', models.PositiveIntegerField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.book')),
            ],
        ),
    ]
