# Generated by Django 4.0 on 2023-01-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_book_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='property_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bookings',
            name='property_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
