# Generated by Django 4.0 on 2022-12-30 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='slot',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
