# Generated by Django 4.0 on 2023-01-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landlords', '0003_listings_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='listings',
            name='property_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_gsl_bike',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_gsl_car',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_gsl_walk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_knustford_bike',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_knustford_car',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_knustford_walk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_lancaster_bike',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_lancaster_car',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_lancaster_walk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_radford_bike',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_radford_car',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_radford_walk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_upsa_bike',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_upsa_car',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_upsa_walk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_wisconsin_bike',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_wisconsin_car',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='listings',
            name='time_to_wisconsin_walk',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
